# Generated by Django 5.1.15 on 2026-09-06 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('address', models.TextField()),
                ('city', models.CharField(default='Hosur', max_length=100)),
                ('state', models.CharField(default='Tamil Nadu', max_length=100)),
                ('pincode', models.CharField(default='635109', max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('cuisine', models.CharField(default='Healthy Food', max_length=150)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('delivery_time', models.IntegerField(default=30)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=30.0, max_digits=6)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating', '-created_at'],
            },
        ),
    ]
