# Generated by Django 5.1.15 on 2026-09-06 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('ingredients', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('calories', models.IntegerField(help_text='Calories in kcal')),
                ('protein', models.DecimalField(decimal_places=1, help_text='Protein in grams', max_digits=6)),
                ('carbohydrates', models.DecimalField(decimal_places=1, help_text='Carbohydrates in grams', max_digits=6)),
                ('fat', models.DecimalField(decimal_places=1, help_text='Fat in grams', max_digits=6)),
                ('food_type', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Vegan', 'Vegan')], default='Veg', max_length=20)),
                ('health_tags', models.CharField(default='Diet Friendly', help_text='Comma-separated tags e.g. High Protein, Low Calorie', max_length=255)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('availability', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_recommended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='foods.category')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-rating', '-created_at'],
            },
        ),
    ]
